version: '3.6'

networks:
  sms: {}

services:
  sms_nginx:
    build: ./nginx
    restart: always
    ports:
      - "80"
    depends_on:
      - sms_flask
    networks:
      - sms

  sms_flask:
    build: ./flask
    restart: always
    expose:
      - 8080
    env_file:
      - ./.env.docker.dev.flask
    command: sh -c "
      python /app/manage.py db upgrade  &&
      uwsgi /app/app.ini"
    networks:
      - sms
    ports:
      - "5432"