version: '3.6'

networks:
  farmer_db:
    name: ${SERVICE_PREFIX}_farmer_db

volumes:
  farmer_db_postgres_data:
    name: ${SERVICE_PREFIX}_farmer_db_postgres_data
    
services:
  farmer_db:
    build: ./farmer_db
    container_name: ${SERVICE_PREFIX}_farmer_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432"
    volumes:
      - farmer_db_postgres_data:/var/lib/postgresql/data
    networks:
      - farmer_db
