"""rename phone to _phone in sms model

Revision ID: 6dc3b9a53f26
Revises: 6ce34720e6ee
Create Date: 2020-08-14 08:06:44.377911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc3b9a53f26'
down_revision = '6ce34720e6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_message', sa.Column('_phone', sa.String(), server_default='[]', nullable=False), schema='sms')
    op.drop_index('ix_sms_sms_message_phone', table_name='sms_message', schema='sms')
    op.drop_column('sms_message', 'phone', schema='sms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_message', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False), schema='sms')
    op.create_index('ix_sms_sms_message_phone', 'sms_message', ['phone'], unique=False, schema='sms')
    op.drop_column('sms_message', '_phone', schema='sms')
    # ### end Alembic commands ###
