"""remove farmer id from sms model

Revision ID: 7b298cf5d220
Revises: ada57ca99268
Create Date: 2020-08-13 07:29:10.807126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b298cf5d220'
down_revision = 'ada57ca99268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_message', 'farmer_id', schema='sms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_message', sa.Column('farmer_id', postgresql.UUID(), autoincrement=False, nullable=True), schema='sms')
    # ### end Alembic commands ###
