"""sms farmer message link

Revision ID: ada57ca99268
Revises: 8bc4fffdfa76
Create Date: 2020-08-12 09:19:18.029846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada57ca99268'
down_revision = '8bc4fffdfa76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_farmer_link',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sms_message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('farmer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['sms_message_id'], ['sms.sms_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sms'
    )
    op.create_index(op.f('ix_sms_sms_farmer_link_sms_message_id'), 'sms_farmer_link', ['sms_message_id'], unique=False, schema='sms')
    op.create_index(op.f('ix_sms_sms_broadcast_subscription_broadcast_id'), 'sms_broadcast_subscription', ['broadcast_id'], unique=False, schema='sms')
    op.drop_index('ix_sms_broadcast_subscription_broadcast_id', table_name='sms_broadcast_subscription', schema='sms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sms_broadcast_subscription_broadcast_id', 'sms_broadcast_subscription', ['broadcast_id'], unique=False, schema='sms')
    op.drop_index(op.f('ix_sms_sms_broadcast_subscription_broadcast_id'), table_name='sms_broadcast_subscription', schema='sms')
    op.drop_index(op.f('ix_sms_sms_farmer_link_sms_message_id'), table_name='sms_farmer_link', schema='sms')
    op.drop_table('sms_farmer_link', schema='sms')
    # ### end Alembic commands ###
